# Generated by Django 4.1.5 on 2023-05-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticwapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='desc',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
    ]
